plugins {
    id "dev.architectury.loom" version "1.9-SNAPSHOT"
    id "maven-publish"
}

sourceCompatibility = targetCompatibility = JavaVersion.VERSION_17

archivesBaseName = project.archives_base_name
version = project.mod_version
group = project.maven_group

loom {
    silentMojangMappingsLicense()
    forge {
        mixinConfigs = [
                "foglooksmodernnow.mixins.json"
        ]
    }
}

repositories {
    maven { url "https://maven.neoforged.net/releases/" }
    exclusiveContent {
        forRepository {
            maven {
                name = "Modrinth"
                url = "https://api.modrinth.com/maven"
            }
        }
        filter {
            includeGroup "maven.modrinth"
        }
    }
}

dependencies {
    minecraft "com.mojang:minecraft:${project.minecraft_version}"
    mappings "net.fabricmc:yarn:${project.yarn_mappings}:v2"
    forge "net.neoforged:forge:${project.forge_version}"

    // I wanna configure stuff
    modImplementation "maven.modrinth:forge-config-screens:${project.fcs_version}"

    // Alex's Caves to test mod compatibility
    modImplementation "maven.modrinth:citadel:${project.citadel_version}"
    modImplementation "maven.modrinth:alexs-caves:${project.alexs_caves_version}"

    // Iris
    modCompileOnly "maven.modrinth:oculus:${project.iris_version}"
}

processResources {
    inputs.property "version", project.version

    filesMatching("META-INF/mods.toml") {
        expand "version": project.version
    }
}

tasks.withType(JavaCompile) {
    options.encoding = "UTF-8"
    options.release = 17
}

java {
    withSourcesJar()
}

jar {
    manifest {
        attributes([
                "Specification-Title"     : project.mod_id,
                "Specification-Vendor"    : project.mod_author,
                "Specification-Version"   : "1",
                "Implementation-Title"    : project.name,
                "Implementation-Version"  : version,
                "Implementation-Vendor"   : project.mod_author,
                "Implementation-Timestamp": new Date().format("yyyy-MM-dd'T'HH:mm:ssZ")
        ])
    }
}

publishing {
    publications {
        mavenJava(MavenPublication) {
            from components.java
        }
    }

    repositories {
    }
}
