# Done to increase the memory available to gradle.
org.gradle.jvmargs=-Xmx1G

# tell architectury loom that this project is a forge project.
# this will enable us to use the "forge" dependency.
# using archloom without this is possible and will give you a
# "standard" loom installation with some extra features.
loom.platform=forge

# Base properties
    # minecraft version
    minecraft_version=1.20.1
    forge_version=1.20.1-47.1.106
    yarn_mappings=1.20.1+build.10

# Mod Properties
    mod_version=1.2.1
    maven_group=net.shizotoaster
    archives_base_name=foglooksmodernnow
    mod_id=foglooksmodernnow
    mod_author=shizotoaster

# Dependencies
    fcs_version=v8.0.2-1.20.1-Forge
    iris_version=1.20.1-1.8.0
    citadel_version=2.6.1
    alexs_caves_version=2.0.2
